Repository sangmandu/SangSangPlus, pull requests merged in 2021-11, with the labels that each got.

#184 2110. 공유기 설치
  Algorithm/SINGON/2110.py
Labels: 어려움, 2시간, 치팅

#185 1300. K번째 수
  Algorithm/SINGON/1300.py
Labels: 어려움, 2시간, 치팅

#177 1012. 유기농 배추 + 2178. 미로 탐색
  Algorithm/HeeRak/1012.py
  Algorithm/HeeRak/2178.py
Labels: 30분, 보통

#187 12015. 가장 긴 증가하는 부분 수열 2
  Algorithm/SINGON/12015.py
Labels: 30분, 1시간, 어려움, 치팅

#188 1694. 숨바꼭질 + 2206. 벽 부수고 이동하기
  Algorithm/HeeRak/1697.py
  Algorithm/HeeRak/2206.py
Labels: 1시간, 어려움, 치팅

#189 1707. 이분 그래프 + 10816. 숫자 카드 2
  Algorithm/HeeRak/10816.py
  Algorithm/HeeRak/1707.py
Labels: 10분, 1시간, 쉬움, 어려움, 치팅

#191 12847. 꿀 아르바이트
  Algorithm/SINGON/12847.py
Labels: 1시간

#190 2805. 나무 자르기 + 2110. 공유기 설치
  Algorithm/HeeRak/2110.py
  Algorithm/HeeRak/2805.py
Labels: 1시간, 어려움

#195 16507. 어두운 건 무서워
  Algorithm/SINGON/16507.py
Labels: 1시간

#196 1451. 직사각형으로 나누기
  Algorithm/SINGON/1451.py
Labels: 1시간, 치팅

#192 1300. K번째 수 + 12015. 가장 긴 증가하는 부분 수열 2 + 12847. 꿀 아르바이트 + 10211. Maximum Subarray
  Algorithm/HeeRak/10211.py
  Algorithm/HeeRak/12015.py
  Algorithm/HeeRak/12847.py
  Algorithm/HeeRak/1300.py
  Algorithm/HeeRak/16507.py
  Algorithm/HeeRak/2725.py
Labels: 30분, 1시간, 보통, 치팅

#198 1451. 직사각형으로 나누기
  Algorithm/HeeRak/1451.py
Labels: 1시간, 치팅

#200 2646. 소형기관차 + 1094. 막대기
  Algorithm/HeeRak/1094.py
  Algorithm/HeeRak/2616.py
Labels: 1시간, 치팅

#202 11723. 집합 + 2961. 도영이가 만든 맛있는 음식
  Algorithm/HeeRak/11723.py
  Algorithm/HeeRak/2961.py
Labels: 1시간, 보통
