Repository sangmandu/SangSangPlus, pull requests merged in 2021-09, with the labels that each got.

#3 1010.다리 놓기
  Algorithm/HeeRak/1010.py
Labels: 30분, 보통

#5 1010.다리 놓기
  Algorithm/SANGMIN/1010.py
Labels: 1시간, 쉬움

#4 1010.다리 놓기
  Algorithm/WOOCHANG/1010.py
Labels: 30분, 보통

#11 1007.벡터 매칭
  Algorithm/SANGMIN/1007.py
Labels: 어려움, 2시간

#12 1007.벡터 매칭
  Algorithm/HeeRak/1007.py
Labels: 어려움, 2시간

#13 1007.벡터 매칭
  Algorithm/WOOCHANG/1007.py
Labels: 미해결, 어려움, 2시간

#22 1449.수리공 항승
  Algorithm/HeeRak/1449.py
Labels: 30분, 보통

#18 1449. 수리공 항승
  Algorithm/SANGMIN/1449.py
Labels: 30분, 보통

#23 1449.수리공 항승
  Algorithm/WOOCHANG/1449.py
Labels: 미해결, 2시간

#29 2012. 등수 매기기
  Algorithm/SINGON/11501.py
  Algorithm/SINGON/2012.py
Labels: 1시간, 보통

#28 2012. 등수 매기기
  Algorithm/SANGMIN/2012.py
Labels: 10분, 쉬움

#32 11501. 주식
  Algorithm/SINGON/11501.py
  Algorithm/SINGON/1931.py
Labels: 1시간, 보통

#27 2012.등수 매기기
  Algorithm/HeeRak/2012.py
Labels: 30분, 쉬움

#38 11501. 주식 + 1931. 회의실 배정
  Algorithm/SANGMIN/11501.py
  Algorithm/SANGMIN/1931.py
Labels: 10분, 1시간, 보통, 쉬움

#42 11501. 주식 + 1931. 회의실 배정
  Algorithm/HeeRak/11051.py
  Algorithm/HeeRak/1931.py
Labels: 30분, 1시간, 보통

#30 2012.등수 매기기 + 11501.주식 + 1931.회의실 배정
  Algorithm/WOOCHANG/11501.py
  Algorithm/WOOCHANG/1931.py
  Algorithm/WOOCHANG/2012.py
Labels: 30분, 1시간, 미해결, 보통, 어려움, 2시간

#45 11047. 동전 0
  Algorithm/SINGON/11047.py
Labels: 쉬움

#49 11047. 동전 0
  Algorithm/SANGMIN/11047.py
Labels: 10분, 쉬움

#47 11047. 동전 0
  Algorithm/HeeRak/11047.py
Labels: 10분, 쉬움

#48 11047. 동전 0
  Algorithm/WOOCHANG/11047.py
Labels: 30분, 쉬움

#51 15903. 카드 합체 놀이
  Algorithm/SINGON/15903
Labels: 30분

#55 15903.카드 합체 놀이
  Algorithm/WOOCHANG/15903.py
Labels: 30분, 쉬움

#54 15903. 카드 합체 놀이
  Algorithm/HeeRak/15903.py
  Algorithm/README.md
Labels: 10분, 쉬움

#53 15093. 카드 합체 놀이
  Algorithm/15093.py
Labels: 10분, 쉬움

#56 1946. 신입 사원
  Algorithm/SINGON/1946.py
Labels: 30분

#68 1946. 신입 사원
  Algorithm/SANGMIN/1946.py
Labels: 30분, 쉬움

#65 1946. 신입 사원
  Algorithm/SANGJUN/1946.py
Labels: 30분, 1시간, 어려움

#57 1946. 신입 사원
  Algorithm/WOOCHANG/1946.py
Labels: 1시간, 보통

#58 1946. 신입 사원
  Algorithm/HeeRak/1946.py
Labels: 1시간, 어려움

#70 11000. 강의실 배정
  Algorithm/SANGMIN/11000.py
Labels: 30분, 보통

#73 11000. 강의실 배정
  Algorithm/SANGJUN/11000.py
Labels: 미해결, 어려움, 2시간

#72 11000. 강의실 배정
  Algorithm/HeeRak/11000.py
Labels: 1시간, 어려움

#71 11000.강의실 배정
  Algorithm/WOOCHANG/11000.py
Labels: 미해결, 어려움, 2시간

#76 13305. 주유소
  Algorithm/SANGMIN/13305.py
Labels: 10분, 쉬움

#78 13305. 주유소
  Algorithm/HeeRak/13305.py
Labels: 10분, 쉬움

#80 13305.주유소
  Algorithm/WOOCHANG/13305.py
Labels: 30분, 쉬움

#81 2167. 2차원 배열의 합
  Algorithm/SINGON/2167.py
Labels: 1시간

#88 2167. 2차원 배열의 합
  Algorithm/HeeRak/2167.py
Labels: 30분, 1시간, 미해결

#87 2167. 2차원 배열의 합
  Algorithm/SANGJUN/2167.py
Labels: 미해결, 어려움, 2시간

#89 2167.2차원 배열의 합
  Algorithm/WOOCHANG/2167.py
Labels: 미해결, 어려움, 2시간

#82 2167. 2차원 배열의 합 + 11441. 합 구하기
  Algorithm/11441.py
  Algorithm/SANGMIN/2167.py
Labels: 10분, 보통, 쉬움

#92 11441. 합 구하기
  Algorithm/SINGON/11441.py
Labels: 10분, 쉬움

#94 11441. 합 구하기
  Algorithm/HeeRak/11441.py
Labels: 10분, 쉬움
